### ISSUE TITLE
Bot doesn't Start

### ISSUE THREAD

**Issue by minion6011** [xMistt/rebootpy#10]
Traceback (most recent call last):
  File "C:\Users\Coso\Desktop\tester\main.py", line 5, in <module>
    bot = commands.Bot(
          ^^^^^^^^^^^^^
  File "C:\Users\Coso\AppData\Roaming\Python\Python311\site-packages\rebootpy\ext\commands\bot.py", line 133, in __init__
    super().__init__(auth, **kwargs)
  File "C:\Users\Coso\AppData\Roaming\Python\Python311\site-packages\rebootpy\ext\commands\core.py", line 1146, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Coso\AppData\Roaming\Python\Python311\site-packages\rebootpy\client.py", line 2597, in __init__
    super().__init__(auth=auth, **kwargs)
  File "C:\Users\Coso\AppData\Roaming\Python\Python311\site-packages\rebootpy\client.py", line 502, in __init__
    self.http = HTTPClient(
                ^^^^^^^^^^^
  File "C:\Users\Coso\AppData\Roaming\Python\Python311\site-packages\rebootpy\http.py", line 407, in __init__
    self._jar = aiohttp.CookieJar()
                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Coso\AppData\Roaming\Python\Python311\site-packages\aiohttp\cookiejar.py", line 89, in __init__
    super().__init__(loop=loop)
  File "C:\Users\Coso\AppData\Roaming\Python\Python311\site-packages\aiohttp\abc.py", line 172, in __init__
    self._loop = loop or asyncio.get_running_loop()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

**Comment by xMistt** [comment]
its been fixed in the current version of the library
